package edu.poly.common;

public enum PageType {
	USER_MANAGEMENT_PAGE, REPORT_MANAGEMENT_PAGE, VIDEO_MANAGEMENT_PAGE,
	SITE_HOME_PAGE, SITE_LOGIN_PAGE,SITE_DANGKY_PAGE, SITE_DOIMATKHAU_PAGE,
	SITE_QUENMATKHAU_PAGE, SITE_EDITTHONGTIN_PAGE, SITE_DETAIL_PAGE,
	SITE_FAVORITE_PAGE, SITE_SHARE_PAGE
}
